# Generated by Django 5.2.1 on 2025-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_poster_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
