# Generated by Django 5.2.1 on 2025-06-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_trailer_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
    ]
