# Generated by Django 5.2.1 on 2025-06-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_mobile_number_booking_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
    ]
