# Generated by Django 5.2.1 on 2025-06-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.show'),
        ),
    ]
