# Generated by Django 5.2.1 on 2025-06-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seat_show'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('show', 'seat_number')},
        ),
    ]
