# Generated by Django 5.2.1 on 2025-07-14 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available_theaters',
            field=models.ManyToManyField(blank=True, help_text='Leave empty ⟹ schedule in EVERY theater. Select one or more ⟹ schedule ONLY in those theaters.', to='core.theater'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.show'),
            preserve_default=False,
        ),
    ]
