# Generated by Django 5.2.1 on 2025-07-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_movie_available_theaters_alter_seat_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#ffc107', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seatclass'),
        ),
        migrations.CreateModel(
            name='ShowPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seatclass')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.show')),
            ],
            options={
                'unique_together': {('show', 'seat_class')},
            },
        ),
    ]
