# Generated by Django 5.2.1 on 2025-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seatclass_seat_seat_class_showprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatclass',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=6),
        ),
    ]
