# Generated by Django 5.2.1 on 2025-07-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seatclass_default_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.seatclass'),
        ),
    ]
