# Generated by Django 5.2.1 on 2025-09-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_seat_seat_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('movie', 'theater', 'show_time')},
        ),
    ]
