# Generated by Django 5.2.1 on 2025-09-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_show_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set(),
        ),
    ]
